[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build:production && npm run prisma:migrate:deploy"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
