[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build:production"

[deploy]
startCommand = "npm run prisma:migrate:deploy && npm run build:backend && node backend/dist/backend/src/server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
